import * as En from 'blockly/msg/en';

export default {
    ...En,
    TNY_CTG_EVENTS: "Events",
    TNY_CTG_CONTROLS: "Controls",
    TNY_CTG_MATHS: "Maths",
    TNY_CTG_TEXT: "Text",
    TNY_CTG_INPUTS: "Inputs",
    TNY_CTG_VARIABLES: "Variables",
    TNY_CTG_LISTS: "Lists",
    TNY_CTG_FUNCTIONS: "Functions",
    TNY_CTG_JOINTS: "Joints",
    TNY_CTG_COLORS: "Colors",
    TNY_SETUP_TITLE: "Setup",
    TNY_LOOP_TITLE: "Loop",
    JOINT_GET_ROTATION: "Get angle of joint %1",
    JOINT_SET_ROTATION: "Set angle of joint %1 to %2 degrees",
    JOINT_ROTATE_BY: "Rotate joint %1 by %2 degrees",
    JOINT_ENABLE: "Enable joint %1",
    JOINT_DISABLE: "Disable joint %1",
    JOINT_SET_BODY_POSTURE: "Set body posture to Rotation X: %1°, Rotation Y: %2°, Rotation Z: %3°, Position X: %4 cm, Position Y: %5 cm, Position Z: %6 cm",
    CONTROLS_WAIT_SECONDS: "Wait %1 seconds",
    TNY_EAR_LEFT: "Left ear",
    TNY_EAR_RIGHT: "Right ear",
    TNY_HIP_ROLL_FL: "Front left hip (roll)",
    TNY_HIP_ROLL_FR: "Front right hip (roll)",
    TNY_HIP_ROLL_BL: "Back left hip (roll)",
    TNY_HIP_ROLL_BR: "Back right hip (roll)",
    TNY_HIP_PITCH_FL: "Front left hip (pitch)",
    TNY_HIP_PITCH_FR: "Front right hip (pitch)",
    TNY_HIP_PITCH_BL: "Back left hip (pitch)",
    TNY_HIP_PITCH_BR: "Back right hip (pitch)",
    TNY_KNEE_PITCH_FL: "Front left knee (pitch)",
    TNY_KNEE_PITCH_FR: "Front right knee (pitch)",
    TNY_KNEE_PITCH_BL: "Back left knee (pitch)",
    TNY_KNEE_PITCH_BR: "Back right knee (pitch)",
}