import * as En from 'blockly/msg/en';

export default {
    ...En,
    TNY_CTG_EVENTS: "Events",
    TNY_CTG_CONTROLS: "Controls",
    TNY_CTG_MATHS: "Maths",
    TNY_CTG_INPUTS: "Inputs",
    TNY_CTG_VARIABLES: "Variables",
    TNY_CTG_LISTS: "Lists",
    TNY_CTG_FUNCTIONS: "Functions",
    TNY_CTG_MOTORS: "Motors",
    TNY_CTG_COLORS: "Colors",
    TNY_SETUP_TITLE: "Setup",
    TNY_LOOP_TITLE: "Loop",
    MOTORS_GET_ROTATION: "Get rotation of motor %1",
    MOTORS_SET_ROTATION: "Set rotation of motor %1 to %2 degrees",
    MOTORS_ROTATE_BY: "Rotate motor %1 by %2 degrees",
    CONTROLS_WAIT_SECONDS: "Wait %1 seconds",
    TNY_EAR_LEFT: "Left ear",
    TNY_EAR_RIGHT: "Right ear",
    TNY_SHOULDER_FRONT_LEFT: "Front left shoulder",
    TNY_SHOULDER_FRONT_RIGHT: "Front right shoulder",
    TNY_SHOULDER_BACK_LEFT: "Back left shoulder",
    TNY_SHOULDER_BACK_RIGHT: "Back right shoulder",
    TNY_LEG_FRONT_LEFT: "Front left leg",
    TNY_LEG_FRONT_RIGHT: "Front right leg",
    TNY_LEG_BACK_LEFT: "Back left leg",
    TNY_LEG_BACK_RIGHT: "Back right leg",
    TNY_ELBOW_FRONT_LEFT: "Front left knee",
    TNY_ELBOW_FRONT_RIGHT: "Front right knee",
    TNY_ELBOW_BACK_LEFT: "Back left knee",
    TNY_ELBOW_BACK_RIGHT: "Back right knee",
}