import * as Fr from 'blockly/msg/fr';

export default {
    ...Fr,
    TNY_CTG_EVENTS: "Événements",
    TNY_CTG_CONTROLS: "Contrôles",
    TNY_CTG_MATHS: "Maths",
    TNY_CTG_INPUTS: "Entrées",
    TNY_CTG_VARIABLES: "Variables",
    TNY_CTG_LISTS: "Listes",
    TNY_CTG_FUNCTIONS: "Fonctions",
    TNY_CTG_MOTORS: "Moteurs",
    TNY_CTG_COLORS: "Couleurs",
    TNY_SETUP_TITLE: "Initialisation",
    TNY_LOOP_TITLE: "Boucle",
    MOTORS_GET_ROTATION: "Obtenir la rotation du moteur %1",
    MOTORS_SET_ROTATION: "Définir la rotation du moteur %1 à %2 degrés",
    MOTORS_ROTATE_BY: "Faire tourner le moteur %1 de %2 degrés",
    CONTROLS_WAIT_SECONDS: "Attendre %1 secondes",
    TNY_EAR_LEFT: "Oreille gauche",
    TNY_EAR_RIGHT: "Oreille droite",
    TNY_SHOULDER_FRONT_LEFT: "Épaule avant gauche",
    TNY_SHOULDER_FRONT_RIGHT: "Épaule avant droite",
    TNY_SHOULDER_BACK_LEFT: "Épaule arrière gauche",
    TNY_SHOULDER_BACK_RIGHT: "Épaule arrière droite",
    TNY_LEG_FRONT_LEFT: "Patte avant gauche",
    TNY_LEG_FRONT_RIGHT: "Patte avant droite",
    TNY_LEG_BACK_LEFT: "Patte arrière gauche",
    TNY_LEG_BACK_RIGHT: "Patte arrière droite",
    TNY_ELBOW_FRONT_LEFT: "Genou avant gauche",
    TNY_ELBOW_FRONT_RIGHT: "Genou avant droit",
    TNY_ELBOW_BACK_LEFT: "Genou arrière gauche",
    TNY_ELBOW_BACK_RIGHT: "Genou arrière droit",
}
