import * as Fr from 'blockly/msg/fr';

export default {
    ...Fr,
    TNY_CTG_EVENTS: "Événements",
    TNY_CTG_CONTROLS: "Contrôles",
    TNY_CTG_MATHS: "Maths",
    TNY_CTG_TEXT: "Texte",
    TNY_CTG_INPUTS: "Entrées",
    TNY_CTG_VARIABLES: "Variables",
    TNY_CTG_LISTS: "Listes",
    TNY_CTG_FUNCTIONS: "Fonctions",
    TNY_CTG_JOINTS: "Articulations",
    TNY_CTG_COLORS: "Couleurs",
    TNY_SETUP_TITLE: "Initialisation",
    TNY_LOOP_TITLE: "Boucle",
    JOINT_GET_ROTATION: "Obtenir l'angle de l'articulation %1",
    JOINT_SET_ROTATION: "Définir l'angle de l'articulation %1 à %2 degrés",
    JOINT_ROTATE_BY: "Faire tourner l'articulation %1 de %2 degrés",
    JOINT_ENABLE: "Activer l'articulation %1",
    JOINT_DISABLE: "Désactiver l'articulation %1",
    JOINT_SET_BODY_POSTURE: "Définir la posture du corps à Rotation X: %1°, Rotation Y: %2°, Rotation Z: %3°, Position X: %4 cm, Position Y: %5 cm, Position Z: %6 cm",
    CONTROLS_WAIT_SECONDS: "Attendre %1 secondes",
    TNY_EAR_LEFT: "Oreille gauche",
    TNY_EAR_RIGHT: "Oreille droite",
    TNY_HIP_ROLL_FL: "hanche avant gauche (Rouli)",
    TNY_HIP_ROLL_FR: "hanche avant droite (Rouli)",
    TNY_HIP_ROLL_BL: "hanche arrière gauche (Rouli)",
    TNY_HIP_ROLL_BR: "hanche arrière droite (Rouli)",
    TNY_HIP_PITCH_FL: "hanche avant gauche (Tangage)",
    TNY_HIP_PITCH_FR: "hanche avant droite (Tangage)",
    TNY_HIP_PITCH_BL: "hanche arrière gauche (Tangage)",
    TNY_HIP_PITCH_BR: "hanche arrière droite (Tangage)",
    TNY_KNEE_PITCH_FL: "genou avant gauche (Tangage)",
    TNY_KNEE_PITCH_FR: "genou avant droite (Tangage)",
    TNY_KNEE_PITCH_BL: "genou arrière gauche (Tangage)",
    TNY_KNEE_PITCH_BR: "genou arrière droite (Tangage)",
}
